"""add line_items to orders

Revision ID: 46ac01109cd2
Revises: 8b6a3c5ad7bb
Create Date: 2026-07-29 22:43:05.445831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46ac01109cd2'
down_revision: Union[str, None] = '8b6a3c5ad7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('line_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'line_items')
    # ### end Alembic commands ###
